startTime: 1
stopTime: 100
EXPERIMENT: 'experiment4'
MODELS_PATH: ['..','models']
DATA_PATH: ['..','data']
MAIN_MODEL_NAME: 'BSN_fxd'
MAIN_MODEL_FILE: 'BSN_fxd.mo'
RESULT_COLUMNS: 
    - Abpd.measurement
    - Abpd.risk_pct
    - Abpd.sig_battery_on
    - Abpd.sig_collected
    - Abpd.sig_processed
    - Abpd.dataTransfer.sig_transfered
    - Abpd.sig_transfered
    - Abpd.battery.cell.SOC
    - Abpd.context
    - Abps.measurement
    - Abps.risk_pct
    - Abps.sig_battery_on
    - Abps.sig_collected
    - Abps.sig_processed
    - Abps.dataTransfer.sig_transfered
    - Abps.sig_transfered
    - Abps.battery.cell.SOC
    - Abps.context
    - HeartRate.measurement
    - HeartRate.risk_pct
    - HeartRate.sig_battery_on
    - HeartRate.sig_collected
    - HeartRate.sig_processed
    - HeartRate.dataTransfer.sig_transfered
    - HeartRate.sig_transfered
    - HeartRate.battery.cell.SOC
    - HeartRate.context
    - Oximeter.measurement
    - Oximeter.risk_pct
    - Oximeter.sig_battery_on
    - Oximeter.sig_collected
    - Oximeter.sig_processed
    - Oximeter.dataTransfer.sig_transfered
    - Oximeter.sig_transfered
    - Oximeter.battery.cell.SOC
    - Oximeter.context
    - temperature.measurement
    - temperature.risk_pct
    - temperature.sig_battery_on
    - temperature.sig_collected
    - temperature.sig_processed
    - temperature.sig_transfered
    - temperature.dataTransfer.sig_transfered
    - temperature.battery.cell.SOC
    - temperature.context
    - CentralNode.sig_processed
    - CentralNode.sig_detected
    - CentralNode.sig_abpd_processed
    - CentralNode.sig_abps_processed
    - CentralNode.sig_heartrate_processed
    - CentralNode.sig_oximeter_processed
    - CentralNode.sig_temperature_processed
    - CentralNode.sig_emergency
    - CentralNode.detect.patient_risk
    - CentralNode.data_fuse.overall_risk
    - CentralNode.battery.cell.SOC
    - CentralNode.battery.SIG_BATTERY_ON
    - CentralNode.detect.risk
    - collectedProcessedObs_abpd.Initial.active
    - collectedProcessedObs_abpd.collectedReached.active
    - collectedProcessedObs_abpd.error.active
    - collectedProcessedObs_abps.Initial.active
    - collectedProcessedObs_abps.collectedReached.active
    - collectedProcessedObs_abps.error.active
    - collectedProcessedObs_hr.Initial.active
    - collectedProcessedObs_hr.collectedReached.active
    - collectedProcessedObs_hr.error.active
    - collectedProcessedObs_ox.Initial.active
    - collectedProcessedObs_ox.collectedReached.active
    - collectedProcessedObs_ox.error.active
    - collectedProcessedObs_temp.Initial.active
    - collectedProcessedObs_temp.collectedReached.active
    - collectedProcessedObs_temp.error.active