states:
  0:
    - 0
    - 32
  1:
    - 32
    - 36
  2:
    - 36
    - 38
  3:
    - 38
    - 41
  4:
    - 41
    - 100

transition_matrix: 
  - - 0.06
    - 0.25
    - 0.56
    - 0.12
    - 0.
  - - 0.
    - 0.64
    - 0.35
    - 0.01
    - 0.
  - - 0.
    - 0.05
    - 0.9
    - .05
    - 0.
  - - 0.
    - 0.01
    - 0.3
    - .69
    - 0.
  - - 0.
    - 0.
    - 0.
    - 0.33
    - 0.67