states:
  0:
    - 0
    - 70
  1:
    - 70
    - 85
  2:
    - 85
    - 97
  3:
    - 97
    - 115
  4:
    - 115
    - 300

transition_matrix:
  - - 0.82
    - 0.15
    - 0.01
    - 0.01
    - 0.
  - - 0.12
    - 0.74
    - 0.12
    - 0.02
    - 0.01
  - - 0.02
    - 0.18
    - 0.66
    - 0.13
    - 0.01
  - - 0.01
    - 0.03
    - 0.18
    - 0.7
    - 0.08
  - - 0.01
    - 0.02
    - 0.03
    - 0.22
    - 0.72